config/routes.rb
Rails.application.routes.draw do

  devise_for :users

    scope :admin do
      root 'dishes#index'
  resources :restaurants
  resources :dishes

      end

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_attached_file :picture, styles: {medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  has_many :dishes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  http_basic_authenticate_with name: 'admin', password: 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/dishes_controller.rb
class DishesController < AdminController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]


  def index
    @dishes = Dish.all
  end


  def show
  end


  def new
    @dish = Dish.new
  end


  def edit
  end


  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
    end
  end

  private

    def set_dish
      @dish = Dish.find(params[:id])
    end


    def dish_params
      params.require(:dish).permit(:name, :price, :description)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < AdminController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  def index
    @restaurants = Restaurant.all
  end


  def show
    @restaurant = Restaurant.find(params[:id])
  end


  def new
    @restaurant = Restaurant.new
  end


  def edit
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
    end
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end


  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :picture, :picture_file_name)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Restaurant Admin', dishes_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Dishes', dishes_path %></li>
        <li><%= link_to 'Restaurant', restaurants_path %></li>
      </ul>
      <!--<ul class="nav navbar-nav navbar-right">-->
        <!--<li><%= link_to 'View shop', root_path %></li>-->
      <!--</ul>-->
    </div>
  </div>
</nav>

app/views/dishes/_form.html.erb
<%= form_for @dish, html: {class: 'form-horizontal'} do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
      <%= f.label :price, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :restaurant, class: 'col-sm-2 control-label' %> <br/>
      <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name, {}, class: 'form-control'  %><br/>
    </div>


    <div class="btn btn-success">
      <%= f.submit %>
    </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><%= dish.price %></td>
        <td><%= dish.description %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li><a href="#">View orders</a></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'admin/navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cafe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= image_tag restaurant.picture.url %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Picture:</strong>

  <%= image_tag @restaurant.picture.url(:medium) %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>